### ISSUE TITLE
Port inside .env

### ISSUE THREAD

**Issue by EliasSalom** [Fullstack-Alfanar/First_FullStack_repo#3]
https://github.com/Fullstack-Alfanar/First_FullStack_repo/blob/80722322934cf95c23c5d3f4c2119e36f70e8145/Back-End/server.js#L9

this also need to be on the `.env` file

**Comment by reemaRahhal** [comment]
I opened a new branch and fixed according to the comment and put  the port at .env file

**Comment by EliasSalom** [comment]
yes, you fixed it
